name: colorahtzee
description: A Yahtzee clone with a color theme.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_exit_app: ^1.1.2

  flutter_bloc: ^8.1.2

  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/dice/
    - assets/images/general/
    - assets/images/letters/
    - assets/images/numbers/
    - assets/images/roll_counts/
    - assets/images/scorecard/

  fonts:
    - family: OctoberCrow
      fonts:
        - asset: fonts/OctoberCrow.ttf